### ISSUE TITLE
No module named 'environs'

### ISSUE THREAD

**Issue by saurya3d** [sahasrara62/filed_payments#1]
settings.py :-from environs import Env

ModuleNotFoundError: No module named 'environs'
 
how to fix this?
(filed_payments-2QEzZojn) env is working fine. while flask run command i'm getting above error

**Comment by sahasrara62** [comment]
Hi @saurya3d ,

Thanks for pointing this out. There was error from my end, as i had mixed up the requirments in pipfile and pipfile.lock while isntalling the package using pipenv and pip seperately in the virtual env during development phase.

I updated the repo and requirements.txt, pipfile, pipfile.lock to latest packages. 

to solve/fix issue.

1. go to project pipenv shell
2. run `pipenv sync` to  make all project dependencies upto date
3. if any package is missing or not found then use `pipenv install <package name>` , not `pip install <package name>` as it won't update the package installation history in pipfile and pipfile.lock
4. then update the reuqirements,txt file by runnning `pipenv run pip freeze > requirements.txt`


if you still face any issue, after following the above steps, please tell me.

In case this solve the issue, please close the issue.

**Comment by saurya3d** [comment]
ERROR collecting test_external_payment.py
ImportError while importing test module 'C:\Users\saura\filed_payments\application\test\test_external_payment.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
c:\users\saura\appdata\local\programs\python\python39\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
..\__init__.py:2: in <module>
    from . import settings
..\settings.py:10: in <module>
    from environs import Env
   ModuleNotFoundError: No module named 'environs'


Before this error  was getting at time of flask run. Now error is while i ran  "pytest test_external_payment.py"  command from another terminal.

**Comment by sahasrara62** [comment]
hi @saurya3d ,

In another terminal, you need to activate the pipenv shell again, ie you need to work on same python environment as the project.

Thanks
Prashant
